spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.138.139:5432/app-employee-security-db
    username: sqluser
    password: D3v310p34202x-GD
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: never
  main:
    allow-bean-definition-overriding=true:
springdoc:
  packages-to-scan: 'link.grooverdev.web.api.employeesecurity.controller'
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %p %c{1.} [%t] %m%n"
  level:
    org.springframework.web: ERROR
    link.grooverdev.web.api: DEBUG
    org.hibernate: ERROR
  file:
    name: icei-app-employees.log
server:
  port: 9030
grooverdev:
  jwt:
    secret: 'miZ8VP1MH6p7jBZVe/e5pEfS3GlX8jC8zkuia9mFJNl2SUZ8vblATv2WdtXGzEn9miZ8VP1MH6p7jBZVe/e5pEfS3GlX8jC8zkuia9mFJNl2SUZ8vblATv2WdtXGzEn9miZ8VP1MH6p7jBZVe/e5pEfS3GlX8jC8zkuia9mFJNl2SUZ8vblATv2WdtXGzEn9'
