spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.138.139:5432/app-employee-security-db
    username: sqluser
    password: D3v310p34202x-GD
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: never
  main:
    allow-bean-definition-overriding=true:
springdoc:
  packages-to-scan: 'tech.icei.web.api.employeesecurity.controller'
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %p %c{1.} [%t] %m%n"
  level:
    org.springframework.web: ERROR
    tech.icei.web.api.appuno: DEBUG
    org.hibernate: ERROR
  file:
    name: icei-app-employees.log
server:
  port: 9030
grooverdev:
  app:
    jwtSecret: '7En81T01chCDGP7XU0oQjfWrb7nMith1bV0RJCn+7JkgyKa1Jgz7zeQFV9bm8f+EgWGFU0G82UX0jRiTHxw8yScH9vruKMOT6m2AtEr9WRrCK5OMIJfegBBwAw4ezQOLivEmGd3JELMpIVcRAq+JBQtPH3wAUfE+PVfu6iOvKnc7Jbbss4XdarzcUyMRiZPD'
    jwtExpirationMs: 86400000

